# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd5c38b5248dc791961c2ba3c40ebd4049bba6cbca7ae03b52bf1cb718806a6e134608ac80d0529bb6fad99fbd184cba017a5129b3175cc697ef69cf71aa816

test:
  secret_key_base: e62566dcf5d1c25873fd57e86e494ada4deb88b4c54252c1e111d3adb4517b1976d8fabd57888e6535888778f890a205c4766ececc01a6bf432a9151e626bfdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
